// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTrW93N0t3VnmInupl97Up1HeQ2vz_ifE',
    appId: '1:31280683326:web:050debd7996400dcef346f',
    messagingSenderId: '31280683326',
    projectId: 'editezy-94f28',
    authDomain: 'editezy-94f28.firebaseapp.com',
    storageBucket: 'editezy-94f28.firebasestorage.app',
    measurementId: 'G-B6NW5ST3BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBleGkxMLYdMldDzuBlJV8GFCxbNjUz0LI',
    appId: '1:31280683326:android:98566c95b43da595ef346f',
    messagingSenderId: '31280683326',
    projectId: 'editezy-94f28',
    storageBucket: 'editezy-94f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOj-DzB61IbuYmIQIu7jpcykDWWexGLgA',
    appId: '1:31280683326:ios:2ffe57266d34ba0fef346f',
    messagingSenderId: '31280683326',
    projectId: 'editezy-94f28',
    storageBucket: 'editezy-94f28.firebasestorage.app',
    iosBundleId: 'com.editeasy.editeasy',
  );
}
